# Project
project_name: "vnav"

# Train
seed: 0
epochs: 10
lr: 0.00001
prob_mask: 0.5
goal_norm_factor: 0.04 # tanh(1)=0.76 tanh(2)=0.96 tanh(3)=0.99
batch_size: 100
num_workers: 8
max_traj_len: -1

# Normalization
action_stats:
  x_max: 1.0
  y_abs_max: 1.0

# Eval
num_diffusion_iters: 10

# Dataset
stride: 5
max_goal_dist: 50
step_distance: 0.11
cam_rot_th: 20 # large camera offset in yaw axis is discarded
goal_rot_th: 20 # small goal offset in yaw axis is discarded

# Model
pred_horizon: 8
context_size: 3
encoding_dim: 256
image_size: [256, 144] # width, height, 16:9

# Log
vis_interval: 5
use_wandb: True

# Paths
datasets_folder: /home/caoruixiang/datasets_mnt/vnav_datasets
logs_folder: /home/caoruixiang/datasets_mnt/vnav_logs
dataset_names: [nadawalk_tokyo]

# Checkpoint
# checkpoint: "vnav-240216-201119"