# Project
project_name: "vnav"

# Train
seed: 0
epochs: 15
lr: 0.00001
prob_mask: 0.5
goal_norm_factor: 0.07 # tanh(1)=0.76 tanh(2)=0.96 tanh(3)=0.99
batch_size: 100
num_workers: 8
max_traj_len: -1

# Normalization
action_stats:
  x_max: 1.0
  y_abs_max: 1.0

# Eval
num_diffusion_iters: 10

# Dataset
stride: 10
max_goal_dist: 20
step_distance: 1.1 # After stride, the distance between two consecutive frames
cam_rot_th: 20 # large camera offset in yaw axis is discarded
goal_rot_th: 10 # small goal offset in yaw axis is discarded

# Model
pred_horizon: 8
context_size: 3
encoding_dim: 256
image_size: [256, 144] # width, height, 16:9

# Log
vis_interval: 5
use_wandb: True

# Paths
datasets_folder: /home/caoruixiang/datasets_mnt/vnav_datasets
logs_folder: /home/caoruixiang/datasets_mnt/vnav_logs
dataset_names: [scalenet, nadawalk_tokyo, tokyotownwalk_shinjukupark]

# Checkpoint
# checkpoint: "vnav-240216-223047"